import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  LOCALE_README_FILES,
  PROMPTS_ORIGINAL_FILE,
  SUPPORTED_LOCALES,
  type Locale,
} from "./config.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOCALES_DIR = path.resolve(__dirname, "../i18n/locales");

export interface Messages {
  langName: string;
  langView: string;
  subtitle: string;
  starCta: string;
  browseGalleryBanner: string;
  gallerySectionTitle: string;
  galleryIntro: string;
  tableThisReadme: string;
  tableSite: string;
  rowPlayback: string;
  rowGenerate: string;
  rowSearch: string;
  rowCopy: string;
  rowUseCases: string;
  rowApi: string;
  cmpReadmePlayback: string;
  cmpSitePlayback: string;
  cmpReadmeGenerate: string;
  cmpSiteGenerate: string;
  cmpReadmeSearch: string;
  cmpSiteSearch: string;
  cmpReadmeCopy: string;
  cmpSiteCopy: string;
  cmpReadmeUseCases: string;
  cmpSiteUseCases: string;
  cmpReadmeApi: string;
  cmpSiteApi: string;
  galleryCta: string;
  tocTitle: string;
  tocGallery: string;
  tocWhatIs: string;
  tocApi: string;
  tocNews: string;
  tocStats: string;
  tocFeatured: string;
  tocAll: string;
  tocContribute: string;
  tocLicense: string;
  tocAck: string;
  whatIsTitle: string;
  whatIsP1: string;
  whatIsP2: string;
  whatIsBullet1: string;
  whatIsBullet2: string;
  whatIsBullet3: string;
  whatIsBullet4: string;
  apiTitle: string;
  apiCta: string;
  newsTitle: string;
  newsLaunched: string;
  statsTitle: string;
  statsMetric: string;
  statsValue: string;
  statsCurated: string;
  statsTotal: string;
  statsModel: string;
  statsUpdated: string;
  featuredTitle: string;
  featuredSubtitle: string;
  allPromptsTitle: string;
  moreInGallery: string;
  promptLabel: string;
  imagePromptLabel: string;
  videoPromptLabel: string;
  viewOriginal: string;
  fallbackNote: string;
  playOnSite: string;
  watchRemix: string;
  by: string;
  followers: string;
  contributeTitle: string;
  contributeSteps: string[];
  contributeSee: string;
  licenseTitle: string;
  licenseBody: string;
  ackTitle: string;
  ackBody: string;
  footerGallery: string;
  footerSubmit: string;
  footerStar: string;
  autoGenerated: string;
  originalDocTitle: string;
  originalDocIntro: string;
  originalDocToc: string;
  sourceLocale: string;
  executableOriginalsLink: string;
}

function loadLocale(locale: Locale): Messages {
  const file = path.join(LOCALES_DIR, `${locale}.json`);
  if (!fs.existsSync(file)) {
    throw new Error(
      `Missing ${file}. Run: pnpm sync-i18n` + (locale === "en" ? "" : ` (or pnpm sync-i18n ${locale})`),
    );
  }
  return JSON.parse(fs.readFileSync(file, "utf-8")) as Messages;
}

const messages: Record<Locale, Messages> = Object.fromEntries(
  SUPPORTED_LOCALES.map((locale) => [locale, loadLocale(locale)]),
) as Record<Locale, Messages>;

export function t(locale: Locale, key: keyof Messages, modelName: string): string {
  const raw = messages[locale][key];
  if (typeof raw === "string") return raw.replace(/\{model\}/g, modelName);
  return raw as unknown as string;
}

export function tList(locale: Locale, key: "contributeSteps", modelName: string): string[] {
  return messages[locale][key].map((s) => s.replace(/\{model\}/g, modelName));
}

/** evolink-style language switcher badges */
export function languageNav(current: Locale): string {
  const flags: Record<Locale, string> = {
    en: "🇺🇸",
    es: "🇪🇸",
    pt: "🇵🇹",
    ja: "🇯🇵",
    ko: "🇰🇷",
    de: "🇩🇪",
    fr: "🇫🇷",
    tr: "🇹🇷",
    "zh-TW": "🇹🇼",
    "zh-CN": "🇨🇳",
    ru: "🇷🇺",
  };

  const lines = SUPPORTED_LOCALES.map((locale) => {
    const m = messages[locale];
    const isCurrent = locale === current;
    const color = isCurrent ? "111111" : "lightgrey";
    const action = encodeURIComponent(isCurrent ? m.langView : m.langView);
    const name = encodeURIComponent(`${flags[locale]} ${m.langName}`);
    const file = LOCALE_README_FILES[locale];
    return `[![${m.langName}](https://img.shields.io/badge/${name}-${action}-${color})](${file})`;
  });

  return lines.join("\n") + "\n\n";
}

export function originalPromptAnchor(id: string): string {
  return `prompt-${id}`;
}

export function originalPromptLink(id: string): string {
  return `${PROMPTS_ORIGINAL_FILE}#${originalPromptAnchor(id)}`;
}
