/**
 * README section renderers.
 *
 * - Localized READMEs: translation layer (readable) + link to PROMPTS_ORIGINAL.md
 * - PROMPTS_ORIGINAL.md: source layer only (text / image / video)
 */
import {
  FEATURED_COUNT,
  GITHUB_REPO,
  MAX_ALL_PROMPTS,
  MODEL_NAME,
  PROMPTS_ORIGINAL_FILE,
  SITE_URL,
  mediaTypeLabel,
  siteUrl,
  type Locale,
} from "./config.js";
import { compact, cleanPrompt, formatDate, oneLine } from "./format.js";
import type { MaterialItem } from "./api-client.js";
import {
  languageNav,
  originalPromptLink,
  t,
  tList,
} from "./i18n.js";

const REPO_URL = `https://github.com/${GITHUB_REPO}`;
const ISSUE_NEW = `${REPO_URL}/issues/new?template=submit-prompt.yml`;

// ---------------------------------------------------------------------------
// Top-level assemblers
// ---------------------------------------------------------------------------

export function generateReadme(items: MaterialItem[], locale: Locale): string {
  const featured = items.slice(0, FEATURED_COUNT);
  const rest = items.slice(FEATURED_COUNT);
  const shown = rest.slice(0, MAX_ALL_PROMPTS - FEATURED_COUNT);
  const hidden = items.length - (featured.length + shown.length);

  return [
    header(items.length, locale),
    galleryCTA(locale),
    toc(locale),
    whatIs(locale),
    apiSection(locale),
    news(locale),
    stats(items.length, locale),
    featuredSection(featured, locale),
    allPromptsSection(shown, hidden, locale),
    contribute(locale),
    footer(locale),
  ].join("");
}

export function generateOriginalPrompts(items: MaterialItem[]): string {
  let md = `# ${messagesOriginalTitle()}\n\n`;
  md += t("en", "originalDocIntro", MODEL_NAME) + "\n\n";
  md += `> ${t("en", "autoGenerated", MODEL_NAME)} · ${SITE_URL.replace(/^https?:\/\//, "")}\n\n`;
  md += `## ${t("en", "originalDocToc", MODEL_NAME)}\n\n`;
  md += items.map((m, i) => `- [${i + 1}. ${cardTitleSource(m)}](#${anchorId(m.id)})`).join("\n");
  md += "\n\n---\n\n";

  items.forEach((m, i) => {
    md += originalCard(m, i + 1);
  });

  md += `\n---\n\n<div align="center">\n\n`;
  md += `[README.md](README.md) · [${t("en", "footerGallery", MODEL_NAME)}](${siteUrl("", "cta")})\n\n</div>\n`;
  return md;
}

function messagesOriginalTitle(): string {
  return t("en", "originalDocTitle", MODEL_NAME);
}

function anchorId(id: string): string {
  return `prompt-${id}`;
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

function header(total: number, locale: Locale): string {
  return `<div align="center">

# 🎬 Awesome ${MODEL_NAME} Prompts

**${t(locale, "subtitle", MODEL_NAME)}**

${languageNav(locale)}

[![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome)
[![License: CC BY 4.0](https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg)](https://creativecommons.org/licenses/by/4.0/)
[![Prompts](https://img.shields.io/badge/Prompts-${total}_Curated-111111.svg)](#${slugAnchor(t(locale, "tocAll", MODEL_NAME))})
[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](docs/CONTRIBUTING.md)
[![GitHub stars](https://img.shields.io/github/stars/${GITHUB_REPO}?style=social)](${REPO_URL})

### [🚀 ${t(locale, "browseGalleryBanner", MODEL_NAME)}](${siteUrl("", "banner")})

</div>

> ⭐ ${t(locale, "starCta", MODEL_NAME)}

> 📎 ${t(locale, "executableOriginalsLink", MODEL_NAME)}: [${PROMPTS_ORIGINAL_FILE}](${PROMPTS_ORIGINAL_FILE})

---

`;
}

function slugAnchor(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

function slugTail(): string {
  return MODEL_NAME.toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

// ---------------------------------------------------------------------------
// Gallery CTA
// ---------------------------------------------------------------------------

function galleryCTA(locale: Locale): string {
  const title = t(locale, "gallerySectionTitle", MODEL_NAME);
  return `## 🌐 ${title}

${t(locale, "galleryIntro", MODEL_NAME)}

| | 📄 ${t(locale, "tableThisReadme", MODEL_NAME)} | 🌐 [${t(locale, "tableSite", MODEL_NAME)}](${siteUrl("", "cta")}) |
|---|:---:|:---:|
| ▶️ ${t(locale, "rowPlayback", MODEL_NAME)} | ${t(locale, "cmpReadmePlayback", MODEL_NAME)} | ✅ ${t(locale, "cmpSitePlayback", MODEL_NAME)} |
| 🔍 ${t(locale, "rowSearch", MODEL_NAME)} | ${t(locale, "cmpReadmeSearch", MODEL_NAME)} | ✅ ${t(locale, "cmpSiteSearch", MODEL_NAME)} |
| 📋 ${t(locale, "rowCopy", MODEL_NAME)} | ${t(locale, "cmpReadmeCopy", MODEL_NAME)} | ✅ ${t(locale, "cmpSiteCopy", MODEL_NAME)} |
| 🔌 ${t(locale, "rowApi", MODEL_NAME)} | ${t(locale, "cmpReadmeApi", MODEL_NAME)} | ✅ ${t(locale, "cmpSiteApi", MODEL_NAME)} |

**[→ ${t(locale, "galleryCta", MODEL_NAME)}](${siteUrl("", "cta")})**

---

`;
}

function toc(locale: Locale): string {
  const what = t(locale, "tocWhatIs", MODEL_NAME).replace("{model}", MODEL_NAME);
  const api = t(locale, "tocApi", MODEL_NAME).replace("{model}", MODEL_NAME);
  return `## 📖 ${t(locale, "tocTitle", MODEL_NAME)}

- [🌐 ${t(locale, "tocGallery", MODEL_NAME)}](#${slugAnchor(t(locale, "gallerySectionTitle", MODEL_NAME))})
- [🎬 ${what}](#-${slugTail()})
- [🔌 ${api}](#use-the-${slugTail()}-api)
- [📰 ${t(locale, "tocNews", MODEL_NAME)}](#${slugAnchor(t(locale, "newsTitle", MODEL_NAME))})
- [📊 ${t(locale, "tocStats", MODEL_NAME)}](#${slugAnchor(t(locale, "statsTitle", MODEL_NAME))})
- [⭐ ${t(locale, "tocFeatured", MODEL_NAME)}](#${slugAnchor(t(locale, "featuredTitle", MODEL_NAME))})
- [📋 ${t(locale, "tocAll", MODEL_NAME)}](#${slugAnchor(t(locale, "allPromptsTitle", MODEL_NAME))})
- [🤝 ${t(locale, "tocContribute", MODEL_NAME)}](#${slugAnchor(t(locale, "contributeTitle", MODEL_NAME))})
- [📄 ${t(locale, "tocLicense", MODEL_NAME)}](#${slugAnchor(t(locale, "licenseTitle", MODEL_NAME))})
- [🙏 ${t(locale, "tocAck", MODEL_NAME)}](#${slugAnchor(t(locale, "ackTitle", MODEL_NAME))})

---

`;
}

function whatIs(locale: Locale): string {
  return `## 🎬 ${t(locale, "whatIsTitle", MODEL_NAME)}

${t(locale, "whatIsP1", MODEL_NAME)}

${t(locale, "whatIsP2", MODEL_NAME)}

- 🎥 **${t(locale, "whatIsBullet1", MODEL_NAME)}**
- 🎬 ${t(locale, "whatIsBullet2", MODEL_NAME)}
- ⚡ ${t(locale, "whatIsBullet3", MODEL_NAME)}
- 🔌 ${t(locale, "whatIsBullet4", MODEL_NAME)}

---

`;
}

function apiSection(locale: Locale): string {
  return `## 🔌 ${t(locale, "apiTitle", MODEL_NAME)}

\`\`\`bash
curl https://api.gptproto.com/v1/video/generations \\
  -H "Authorization: Bearer $GPTPROTO_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "model": "seedance-2-0",
    "prompt": "A cinematic slow-motion shot of a paper plane gliding over a neon city at night"
  }'
\`\`\`

👉 **[${t(locale, "apiCta", MODEL_NAME)}](${siteUrl("", "api")})**

---

`;
}

function news(locale: Locale): string {
  const date = new Date().toISOString().slice(0, 10);
  return `## 📰 ${t(locale, "newsTitle", MODEL_NAME)}

- **${date}** — ${t(locale, "newsLaunched", MODEL_NAME)}

---

`;
}

function stats(total: number, locale: Locale): string {
  return `## 📊 ${t(locale, "statsTitle", MODEL_NAME)}

<div align="center">

| ${t(locale, "statsMetric", MODEL_NAME)} | ${t(locale, "statsValue", MODEL_NAME)} |
|---|---|
| 📝 ${t(locale, "statsCurated", MODEL_NAME)} | **${total}** |
| 🎬 ${t(locale, "statsModel", MODEL_NAME)} | **${MODEL_NAME}** |
| 🔄 ${t(locale, "statsUpdated", MODEL_NAME)} | **${formatDate(new Date().toISOString())}** |

</div>

---

`;
}

function featuredSection(items: MaterialItem[], locale: Locale): string {
  if (items.length === 0) return "";
  let md = `## ⭐ ${t(locale, "featuredTitle", MODEL_NAME)}

> ${t(locale, "featuredSubtitle", MODEL_NAME)}

`;
  items.forEach((m, i) => (md += card(m, i + 1, true, locale)));
  return md;
}

function allPromptsSection(items: MaterialItem[], hidden: number, locale: Locale): string {
  let md = `## 📋 ${t(locale, "allPromptsTitle", MODEL_NAME)}

`;
  items.forEach((m, i) => (md += card(m, FEATURED_COUNT + i + 1, false, locale)));

  if (hidden > 0) {
    md += `<div align="center">

### ➕ ${hidden}+ ${t(locale, "moreInGallery", MODEL_NAME)}

**[→ ${t(locale, "galleryCta", MODEL_NAME)}](${siteUrl("", "cta")})**

</div>

---

`;
  }
  return md;
}

function card(m: MaterialItem, index: number, featured: boolean, locale: Locale): string {
  const width = featured ? 640 : 480;
  const title = cardTitleLocalized(m);
  let md = `### ${index}. ${title}\n\n`;

  md += `![Type](https://img.shields.io/badge/${encodeURIComponent(
    mediaTypeLabel(m.media_type_slug, locale),
  )}-${encodeURIComponent(MODEL_NAME)}-111111)`;
  if (m.is_fallback) {
    md += ` ![fallback](https://img.shields.io/badge/translation-pending-lightgrey)`;
  }
  if (featured && m.tweet?.like_count) {
    md += ` ![Likes](https://img.shields.io/badge/❤️-${encodeURIComponent(
      compact(m.tweet.like_count),
    )}-e0245e)`;
  }
  md += `\n\n`;

  md += mediaBlock(m, width, title, locale);
  md += translationPromptBlock(m, locale);
  md += `📎 [${t(locale, "viewOriginal", MODEL_NAME)}](${originalPromptLink(m.id)})\n\n`;
  md += detailsBlock(m, locale);
  md += `**[▶️ ${t(locale, "watchRemix", MODEL_NAME)}](${siteUrl("", "cta")})**\n\n`;
  md += `---\n\n`;
  return md;
}

function cardTitleLocalized(m: MaterialItem): string {
  if (m.title?.trim()) return oneLine(m.title, 70);
  const readable = primaryReadable(m);
  if (readable) return oneLine(readable, 70);
  return `${MODEL_NAME} Prompt`;
}

function cardTitleSource(m: MaterialItem): string {
  const text = primarySourceText(m);
  return text ? oneLine(text, 70) : `${MODEL_NAME} Prompt`;
}

function primaryReadable(m: MaterialItem): string {
  const p = m.prompt;
  if (p.type === "single") return p.readable || p.text || "";
  return p.video_readable || p.image_readable || p.video || p.image || "";
}

function primarySourceText(m: MaterialItem): string {
  const p = m.prompt;
  if (p.type === "single") return p.text || "";
  return p.video || p.image || "";
}

function mediaBlock(m: MaterialItem, width: number, alt: string, locale: Locale): string {
  const media = m.tweet?.media?.[0];
  const href = siteUrl("", "image");
  if (!media) {
    const ref = m.reference_images?.[0];
    if (!ref) return "";
    return `<div align="center">\n<a href="${href}"><img src="${ref.url}" width="${width}" alt="${escapeAttr(
      alt,
    )}"></a>\n</div>\n\n`;
  }

  const src = media.type === "video" ? media.poster || media.url : media.url;
  let block = `<div align="center">\n<a href="${href}"><img src="${src}" width="${width}" alt="${escapeAttr(
    alt,
  )}"></a>\n`;
  if (media.type === "video") {
    block += `<br><sub>▶️ <a href="${href}">${t(locale, "playOnSite", MODEL_NAME)}</a></sub>\n`;
  }
  block += `</div>\n\n`;
  return block;
}

/** Translation layer — shown in localized READMEs. */
function translationPromptBlock(m: MaterialItem, locale: Locale): string {
  const p = m.prompt;
  if (p.type === "dual") {
    let md = "";
    const img = cleanPrompt(p.image_readable || p.image);
    const vid = cleanPrompt(p.video_readable || p.video);
    if (img) md += `**🖼️ ${t(locale, "imagePromptLabel", MODEL_NAME)}**\n\n\`\`\`\n${img}\n\`\`\`\n\n`;
    if (vid) md += `**🎬 ${t(locale, "videoPromptLabel", MODEL_NAME)}**\n\n\`\`\`\n${vid}\n\`\`\`\n\n`;
    return md;
  }
  const text = cleanPrompt(p.readable || p.text);
  if (!text) return "";
  return `**📝 ${t(locale, "promptLabel", MODEL_NAME)}**\n\n\`\`\`\n${text}\n\`\`\`\n\n`;
}

/** Source layer only — for PROMPTS_ORIGINAL.md. */
function sourcePromptBlock(m: MaterialItem): string {
  const p = m.prompt;
  if (p.type === "dual") {
    let md = "";
    if (p.image) md += `**🖼️ Image prompt (source)**\n\n\`\`\`\n${cleanPrompt(p.image)}\n\`\`\`\n\n`;
    if (p.video) md += `**🎬 Video prompt (source)**\n\n\`\`\`\n${cleanPrompt(p.video)}\n\`\`\`\n\n`;
    return md;
  }
  const text = cleanPrompt(p.text);
  if (!text) return "";
  return `**📝 Prompt (source)**\n\n\`\`\`\n${text}\n\`\`\`\n\n`;
}

function originalCard(m: MaterialItem, index: number): string {
  const title = cardTitleSource(m);
  let md = `<a id="${anchorId(m.id)}"></a>\n\n### ${index}. ${title}\n\n`;
  if (m.source_locale) {
    md += `![${t("en", "sourceLocale", MODEL_NAME)}](https://img.shields.io/badge/${encodeURIComponent(
      m.source_locale,
    )}-source-555555)\n\n`;
  }
  md += sourcePromptBlock(m);
  md += detailsBlock(m, "en");
  md += `---\n\n`;
  return md;
}

function detailsBlock(m: MaterialItem, locale: Locale): string {
  const tw = m.tweet;
  if (!tw) return "";

  const verified = tw.author_verified ? " ✓" : "";
  const followers = tw.author_followers
    ? ` · ${compact(tw.author_followers)} ${t(locale, "followers", MODEL_NAME)}`
    : "";
  const profile = `https://x.com/${tw.author_username}`;

  let md = `**${t(locale, "by", MODEL_NAME)}** [${tw.author_name}${verified}](${profile}) (@${tw.author_username})${followers}\n\n`;

  const metrics: string[] = [];
  if (tw.like_count) metrics.push(`❤️ ${compact(tw.like_count)}`);
  if (tw.retweet_count) metrics.push(`🔁 ${compact(tw.retweet_count)}`);
  if (tw.bookmark_count) metrics.push(`🔖 ${compact(tw.bookmark_count)}`);
  if (tw.view_count) metrics.push(`👁 ${compact(tw.view_count)}`);
  if (metrics.length) md += `${metrics.join(" · ")}\n\n`;

  const date = formatDate(tw.posted_at);
  if (date) md += `<sub>📅 ${date}</sub>\n\n`;
  return md;
}

function contribute(locale: Locale): string {
  const steps = tList(locale, "contributeSteps", MODEL_NAME);
  let md = `## 🤝 ${t(locale, "contributeTitle", MODEL_NAME)}

`;
  steps.forEach((step, i) => {
    const line = step.replace("**new prompt submission**", `[**new prompt submission**](${ISSUE_NEW})`);
    md += `${i + 1}. ${line}\n`;
  });
  md += `\n${t(locale, "contributeSee", MODEL_NAME)}\n\n---\n\n`;
  return md;
}

function footer(locale: Locale): string {
  return `## 📄 ${t(locale, "licenseTitle", MODEL_NAME)}

${t(locale, "licenseBody", MODEL_NAME)}

---

## 🙏 ${t(locale, "ackTitle", MODEL_NAME)}

${t(locale, "ackBody", MODEL_NAME)}

---

## ⭐ Star History

[![Star History Chart](https://api.star-history.com/svg?repos=${GITHUB_REPO}&type=Date)](https://star-history.com/#${GITHUB_REPO}&Date)

---

<div align="center">

**[🌐 ${t(locale, "footerGallery", MODEL_NAME)}](${siteUrl("", "cta")})** • **[📝 ${t(locale, "footerSubmit", MODEL_NAME)}](${ISSUE_NEW})** • **[⭐ ${t(locale, "footerStar", MODEL_NAME)}](${REPO_URL})**

<sub>🤖 ${t(locale, "autoGenerated", MODEL_NAME)} · ${SITE_URL.replace(/^https?:\/\//, "")}</sub>

</div>
`;
}

function escapeAttr(s: string): string {
  return s.replace(/"/g, "&quot;");
}
